/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "errors": {
            "internalServerError": string;
            "badRequest": string;
            "unauthorized": string;
            "forbidden": string;
            "notFound": string;
            "conflict": string;
            "unprocessableEntity": string;
            "tooManyRequests": string;
            "serviceUnavailable": string;
        };
        "success": {
            "generic": string;
        };
        "fields": {
            "email": string;
            "password": string;
            "username": string;
        };
        "validation": {
            "required": string;
            "invalid": string;
            "minLength": string;
            "maxLength": string;
            "min": string;
            "max": string;
            "minItems": string;
            "maxItems": string;
            "email": string;
            "url": string;
            "uuid": string;
            "date": string;
            "password_pattern": string;
            "phone_pattern": string;
            "pattern": string;
        };
    };
    "users": {
        "create": {
            "success": string;
            "error": string;
        };
        "update": {
            "success": string;
        };
        "delete": {
            "success": string;
        };
        "validation": {
            "required": string;
            "invalid": string;
            "minLength": string;
            "fields": {
                "email": string;
                "username": string;
                "password": string;
                "name": string;
                "phone": string;
            };
            "password": {
                "pattern": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
