/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "admin": {
        "lockouts": {
            "list_success": string;
            "get_success": string;
            "cleared_success": string;
            "not_found": string;
            "already_cleared": string;
        };
    };
    "auth": {
        "register": {
            "success": string;
        };
        "verify": {
            "success": string;
        };
        "resend": {
            "success": string;
        };
        "refresh": {
            "success": string;
        };
        "login": {
            "success": string;
            "step_up_required": string;
            "step_up_required_totp": string;
            "step_up_required_recovery": string;
        };
        "logout": {
            "success": string;
        };
        "my_lockout": {
            "success": string;
        };
        "success": {
            "no_other_sessions": string;
            "sessions_retrieved": string;
            "sessions_revoked": string;
            "no_sessions_provided": string;
        };
        "errors": {
            "email_already_exists": string;
            "email_already_exists_deleted": string;
            "username_already_exists": string;
            "username_already_exists_deleted": string;
            "user_not_found": string;
            "invalid_credentials": string;
            "account_not_verified": string;
            "account_frozen": string;
            "captcha_required": string;
            "secure_token_invalid": string;
            "already_verified": string;
            "invalid_code": string;
            "code_expired": string;
            "code_still_valid": string;
            "code_still_valid_seconds": string;
            "account_locked": string;
            "account_locked_seconds": string;
            "invalid_code_last_attempt": string;
            "reused_refresh_token": string;
            "session_revoked": string;
            "session_expired": string;
            "invalid_refresh_token": string;
            "invalid_client": string;
            "step_up_expired": string;
            "step_up_invalid_code": string;
            "step_up_too_many_attempts": string;
            "step_up_locked_minutes": string;
            "step_up_locked_hours": string;
            "password_reused": string;
            "password_too_recent": string;
            "step_up_expects_totp": string;
            "step_up_expects_email": string;
            "step_up_expects_passkey": string;
            "step_up_invalid_passkey": string;
            "passkey_login_failed": string;
            "oauth_disabled": string;
            "oauth_failed": string;
            "oauth_email_not_verified": string;
            "oauth_account_unavailable": string;
            "too_many_attempts": string;
            "email_taken": string;
            "reset_token_invalid": string;
        };
        "validation": {
            "code_length": string;
            "code_numeric": string;
        };
        "step_up": {
            "success": string;
            "passkey_options": string;
            "challenge_checked": string;
        };
        "trusted_devices": {
            "list_success": string;
            "revoke_success": string;
            "not_found": string;
        };
        "sudo": {
            "success": string;
            "status_success": string;
            "required": string;
            "invalid_password": string;
            "too_many_attempts": string;
            "invalid_code": string;
            "invalid_passkey": string;
            "passkey_options": string;
        };
        "password": {
            "change_success": string;
        };
        "forgot_password": {
            "success": string;
            "throttled": string;
        };
        "reset_password": {
            "success": string;
            "token_checked": string;
        };
        "secure_account": {
            "success": string;
            "token_checked": string;
        };
        "email_change": {
            "requested": string;
            "success": string;
        };
        "mfa": {
            "status_success": string;
            "enrolment_started": string;
            "enabled": string;
            "disabled": string;
            "recovery_codes_regenerated": string;
            "already_enabled": string;
            "not_started": string;
            "not_enabled": string;
            "invalid_code": string;
            "last_factor": string;
            "passkey": {
                "list_success": string;
                "enrolment_started": string;
                "added": string;
                "renamed": string;
                "removed": string;
                "not_started": string;
                "invalid": string;
                "not_found": string;
            };
        };
    };
    "common": {
        "errors": {
            "internalServerError": string;
            "badRequest": string;
            "unauthorized": string;
            "forbidden": string;
            "admin_only": string;
            "notFound": string;
            "conflict": string;
            "unprocessableEntity": string;
            "tooManyRequests": string;
            "serviceUnavailable": string;
        };
        "success": {
            "generic": string;
        };
        "fields": {
            "email": string;
            "password": string;
            "username": string;
            "name": string;
            "phone": string;
            "avatar": string;
        };
        "validation": {
            "required": string;
            "invalid": string;
            "minLength": string;
            "maxLength": string;
            "min": string;
            "max": string;
            "minItems": string;
            "maxItems": string;
            "email": string;
            "url": string;
            "uuid": string;
            "date": string;
            "password_pattern": string;
            "phone_pattern": string;
            "pattern": string;
        };
    };
    "users": {
        "create": {
            "success": string;
            "error": string;
        };
        "update": {
            "success": string;
        };
        "delete": {
            "success": string;
        };
        "errors": {
            "user_not_found": string;
            "user_already_deleted": string;
            "cannot_update_deleted_user": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
