/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "admin": {
        "lockouts": {
            "list_success": string;
            "get_success": string;
            "cleared_success": string;
            "not_found": string;
            "already_cleared": string;
        };
        "login_lockouts": {
            "created_success": string;
            "list_success": string;
            "get_success": string;
            "cleared_success": string;
            "not_found": string;
            "already_cleared": string;
        };
    };
    "auth": {
        "register": {
            "success": string;
        };
        "verify": {
            "success": string;
        };
        "resend": {
            "success": string;
        };
        "refresh": {
            "success": string;
        };
        "login": {
            "success": string;
        };
        "logout": {
            "success": string;
        };
        "my_lockout": {
            "success": string;
        };
        "security": {
            "compremise": string;
        };
        "success": {
            "no_other_sessions": string;
            "sessions_retrieved": string;
            "sessions_revoked": string;
            "no_sessions_provided": string;
        };
        "duration": {
            "seconds": string;
            "minutes": string;
            "hours": string;
            "days": string;
            "weeks": string;
        };
        "errors": {
            "account_already_exists": string;
            "email_already_exists": string;
            "email_already_exists_deleted": string;
            "username_already_exists": string;
            "username_already_exists_deleted": string;
            "user_not_found": string;
            "invalid_credentials": string;
            "account_not_verified": string;
            "already_verified": string;
            "invalid_code": string;
            "code_expired": string;
            "code_still_valid": string;
            "account_locked": string;
            "verification_locked": string;
            "login_locked": string;
            "invalid_code_last_attempt": string;
            "reused_refresh_token": string;
            "too_many_verification_attempts": string;
            "session_revoked": string;
            "session_expired": string;
            "invalid_refresh_token": string;
            "invalid_client": string;
            "missing_device_secret": string;
            "too_many_login_attempts": string;
            "incorrect_password_last_attempt": string;
            "token_binding_failed": string;
            "invalid_csrf_token": string;
            "phone_not_recognized": string;
            "phone_taken": string;
            "phone_already_verified": string;
            "phone_locked": string;
            "phone_locked_suspicious": string;
            "phone_otp_still_valid": string;
            "phone_otp_expired": string;
            "phone_too_many_attempts": string;
            "phone_invalid_code": string;
            "phone_invalid_code_last_attempt": string;
        };
        "phone": {
            "sent": string;
            "verified": string;
        };
        "validation": {
            "code_length": string;
            "code_numeric": string;
        };
    };
    "common": {
        "errors": {
            "internalServerError": string;
            "badRequest": string;
            "unauthorized": string;
            "forbidden": string;
            "admin_only": string;
            "notFound": string;
            "conflict": string;
            "unprocessableEntity": string;
            "tooManyRequests": string;
            "serviceUnavailable": string;
        };
        "success": {
            "generic": string;
        };
        "fields": {
            "email": string;
            "password": string;
            "username": string;
            "name": string;
            "phone": string;
            "avatar": string;
        };
        "validation": {
            "required": string;
            "invalid": string;
            "minLength": string;
            "maxLength": string;
            "min": string;
            "max": string;
            "minItems": string;
            "maxItems": string;
            "email": string;
            "url": string;
            "uuid": string;
            "date": string;
            "password_pattern": string;
            "phone_pattern": string;
            "pattern": string;
        };
    };
    "users": {
        "create": {
            "success": string;
            "error": string;
        };
        "update": {
            "success": string;
        };
        "delete": {
            "success": string;
        };
        "errors": {
            "user_not_found": string;
            "user_already_deleted": string;
            "cannot_update_deleted_user": string;
            "password_recently_used": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
