
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.FactOrderScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  orderTs: 'orderTs',
  dateId: 'dateId',
  subtotal: 'subtotal',
  taxTotal: 'taxTotal',
  shippingTotal: 'shippingTotal',
  discountTotal: 'discountTotal',
  grandTotal: 'grandTotal',
  marginTotal: 'marginTotal',
  itemCount: 'itemCount',
  status: 'status',
  paymentStatus: 'paymentStatus',
  shippingStatus: 'shippingStatus',
  currency: 'currency',
  source: 'source',
  couponCode: 'couponCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  shippedAt: 'shippedAt',
  deliveredAt: 'deliveredAt'
};

exports.Prisma.FactOrderItemScalarFieldEnum = {
  id: 'id',
  orderItemId: 'orderItemId',
  orderId: 'orderId',
  productId: 'productId',
  productScId: 'productScId',
  dateId: 'dateId',
  orderTs: 'orderTs',
  qty: 'qty',
  unitPrice: 'unitPrice',
  unitCost: 'unitCost',
  taxAmount: 'taxAmount',
  discountAmount: 'discountAmount',
  extendedPrice: 'extendedPrice',
  margin: 'margin',
  variantSku: 'variantSku',
  productName: 'productName',
  categoryName: 'categoryName',
  brandName: 'brandName',
  isReturned: 'isReturned',
  createdAt: 'createdAt'
};

exports.Prisma.FactPaymentScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  orderId: 'orderId',
  dateId: 'dateId',
  timestamp: 'timestamp',
  amount: 'amount',
  currency: 'currency',
  provider: 'provider',
  method: 'method',
  status: 'status',
  errorCode: 'errorCode',
  isSuccess: 'isSuccess',
  createdAt: 'createdAt'
};

exports.Prisma.FactShipmentScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  orderId: 'orderId',
  dateId: 'dateId',
  weight: 'weight',
  cost: 'cost',
  carrier: 'carrier',
  serviceLevel: 'serviceLevel',
  shippedTs: 'shippedTs',
  deliveredTs: 'deliveredTs',
  deliveryDays: 'deliveryDays',
  isOnTime: 'isOnTime',
  createdAt: 'createdAt'
};

exports.Prisma.FactSessionScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  visitorId: 'visitorId',
  dateId: 'dateId',
  startTime: 'startTime',
  endTime: 'endTime',
  durationSec: 'durationSec',
  pageViews: 'pageViews',
  eventsCount: 'eventsCount',
  cartAddCount: 'cartAddCount',
  orderCount: 'orderCount',
  bounce: 'bounce',
  source: 'source',
  medium: 'medium',
  campaign: 'campaign',
  deviceType: 'deviceType',
  browser: 'browser',
  os: 'os',
  country: 'country',
  city: 'city'
};

exports.Prisma.FactPageviewScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  url: 'url',
  path: 'path',
  referrer: 'referrer',
  timestamp: 'timestamp',
  timeOnPageSec: 'timeOnPageSec',
  scrollDepth: 'scrollDepth',
  loadTimeMs: 'loadTimeMs',
  productId: 'productId',
  categoryId: 'categoryId'
};

exports.Prisma.FactSearchScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  timestamp: 'timestamp',
  query: 'query',
  resultCount: 'resultCount',
  clickedResultPos: 'clickedResultPos',
  converted: 'converted'
};

exports.Prisma.FactCartActivityScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  timestamp: 'timestamp',
  action: 'action',
  productId: 'productId',
  sku: 'sku',
  quantityDelta: 'quantityDelta',
  priceSnapshot: 'priceSnapshot'
};

exports.Prisma.FactReviewScalarFieldEnum = {
  id: 'id',
  reviewId: 'reviewId',
  productId: 'productId',
  userId: 'userId',
  dateId: 'dateId',
  timestamp: 'timestamp',
  rating: 'rating',
  hasText: 'hasText',
  hasImages: 'hasImages',
  textLength: 'textLength',
  sentimentScore: 'sentimentScore',
  verified: 'verified'
};

exports.Prisma.DimProductScalarFieldEnum = {
  productScId: 'productScId',
  productId: 'productId',
  sku: 'sku',
  name: 'name',
  categoryId: 'categoryId',
  brandId: 'brandId',
  currentPrice: 'currentPrice',
  costPrice: 'costPrice',
  isActive: 'isActive',
  validFrom: 'validFrom',
  validTo: 'validTo',
  isCurrent: 'isCurrent',
  categoryName: 'categoryName',
  brandName: 'brandName',
  supplier: 'supplier',
  tags: 'tags'
};

exports.Prisma.DimUserScalarFieldEnum = {
  userScId: 'userScId',
  userId: 'userId',
  email: 'email',
  city: 'city',
  country: 'country',
  gender: 'gender',
  ageGroup: 'ageGroup',
  segment: 'segment',
  ltv: 'ltv',
  firstOrderDate: 'firstOrderDate',
  validFrom: 'validFrom',
  validTo: 'validTo',
  isCurrent: 'isCurrent'
};

exports.Prisma.DimDateScalarFieldEnum = {
  dateId: 'dateId',
  date: 'date',
  dayOfWeek: 'dayOfWeek',
  dayName: 'dayName',
  dayOfMonth: 'dayOfMonth',
  weekOfYear: 'weekOfYear',
  month: 'month',
  monthName: 'monthName',
  quarter: 'quarter',
  year: 'year',
  isWeekend: 'isWeekend',
  isHoliday: 'isHoliday',
  fiscalYear: 'fiscalYear',
  fiscalPeriod: 'fiscalPeriod'
};

exports.Prisma.DimMarketingScalarFieldEnum = {
  id: 'id',
  utmSource: 'utmSource',
  utmMedium: 'utmMedium',
  utmCampaign: 'utmCampaign',
  utmTerm: 'utmTerm',
  utmContent: 'utmContent',
  channelGroup: 'channelGroup',
  createdAt: 'createdAt'
};

exports.Prisma.DimLocationScalarFieldEnum = {
  id: 'id',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  country: 'country',
  countryCode: 'countryCode',
  region: 'region'
};

exports.Prisma.IngestOffsetScalarFieldEnum = {
  id: 'id',
  source: 'source',
  partition: 'partition',
  lastOffset: 'lastOffset',
  lastTimestamp: 'lastTimestamp',
  payloadHash: 'payloadHash',
  updatedAt: 'updatedAt'
};

exports.Prisma.StagingRawEventScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  source: 'source',
  payload: 'payload',
  headers: 'headers',
  receivedAt: 'receivedAt',
  processedAt: 'processedAt',
  status: 'status',
  error: 'error',
  retryCount: 'retryCount'
};

exports.Prisma.AggDailyStatsScalarFieldEnum = {
  dateId: 'dateId',
  totalRevenue: 'totalRevenue',
  totalOrders: 'totalOrders',
  totalVisits: 'totalVisits',
  conversionRate: 'conversionRate',
  aov: 'aov',
  updatedAt: 'updatedAt'
};

exports.Prisma.AggProductPerformanceScalarFieldEnum = {
  dateId: 'dateId',
  productId: 'productId',
  views: 'views',
  cartAdds: 'cartAdds',
  purchases: 'purchases',
  revenue: 'revenue',
  returns: 'returns'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  FactOrder: 'FactOrder',
  FactOrderItem: 'FactOrderItem',
  FactPayment: 'FactPayment',
  FactShipment: 'FactShipment',
  FactSession: 'FactSession',
  FactPageview: 'FactPageview',
  FactSearch: 'FactSearch',
  FactCartActivity: 'FactCartActivity',
  FactReview: 'FactReview',
  DimProduct: 'DimProduct',
  DimUser: 'DimUser',
  DimDate: 'DimDate',
  DimMarketing: 'DimMarketing',
  DimLocation: 'DimLocation',
  IngestOffset: 'IngestOffset',
  StagingRawEvent: 'StagingRawEvent',
  AggDailyStats: 'AggDailyStats',
  AggProductPerformance: 'AggProductPerformance'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
