/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "errors": {
            "internalServerError": string;
            "badRequest": string;
            "unauthorized": string;
            "forbidden": string;
            "notFound": string;
            "conflict": string;
            "unprocessableEntity": string;
            "tooManyRequests": string;
            "serviceUnavailable": string;
        };
        "success": {
            "generic": string;
        };
        "fields": {
            "email": string;
            "password": string;
            "name": string;
            "code": string;
            "inviteToken": string;
            "mfaToken": string;
            "roleKey": string;
            "roleKeys": string;
        };
        "validation": {
            "required": string;
            "invalid": string;
            "minLength": string;
            "maxLength": string;
            "min": string;
            "max": string;
            "minItems": string;
            "maxItems": string;
            "email": string;
            "url": string;
            "uuid": string;
            "date": string;
            "pattern": string;
        };
    };
    "staff": {
        "errors": {
            "invite_invalid": string;
            "invite_used": string;
            "code_incorrect": string;
            "invalid_credentials": string;
            "invalid_credentials_remaining": string;
            "too_many_attempts": string;
            "mfa_expired": string;
            "mfa_code_incorrect": string;
            "refresh_invalid": string;
            "refresh_missing": string;
            "session_expired": string;
            "email_exists": string;
            "account_not_found": string;
            "role_not_found": string;
            "role_key_exists": string;
            "role_system_locked": string;
            "cannot_grant": string;
            "cannot_modify_superadmin": string;
            "self_lockout": string;
            "invite_not_pending": string;
            "invitation_not_found": string;
            "invite_already_accepted": string;
            "too_many_invites": string;
            "reset_invalid": string;
        };
        "success": {
            "setup_ready": string;
            "activated": string;
            "mfa_required": string;
            "logged_in": string;
            "refreshed": string;
            "logged_out": string;
            "profile": string;
            "invited": string;
            "list": string;
            "roles": string;
            "permissions": string;
            "role_created": string;
            "role_updated": string;
            "role_deleted": string;
            "role_members": string;
            "audit": string;
            "invitations": string;
            "invite_cancelled": string;
            "invite_resent": string;
            "role_assigned": string;
            "role_removed": string;
            "totp_reset_requested": string;
            "totp_reset_ready": string;
            "totp_reset_done": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
